# Site settings
title: Serverdirect Style Guide
email: siuho@serverdirect.nl
description: Style guide with Jekyll
baseurl: ""
url: "https://www.serverdirect.nl/jekyllstyleguide" # the base hostname & protocol for your site
twitter_username: siubox
github_username:  siubox

# Collections
collections:
  components:
    output: false

# Front Matter Defaults

# General settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
sass:
  sass_dir: _sass
  style: :compressed
